DROP TABLE IF EXISTS withdrawal_outcomes;
DROP TABLE IF EXISTS wallet_ledger;
DROP TABLE IF EXISTS wallets;

CREATE TABLE wallets (
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    balance BIGINT NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE wallet_ledger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id VARCHAR(36) NOT NULL,
    entry_type VARCHAR(16) NOT NULL,
    amount BIGINT NOT NULL,
    balance_after BIGINT NOT NULL,
    idempotency_key VARCHAR(128),
    description VARCHAR(512),
    transaction_id VARCHAR(64),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_wallet_ledger_wallet FOREIGN KEY (wallet_id) REFERENCES wallets (id),
    CONSTRAINT uk_wallet_ledger_transaction_id UNIQUE (transaction_id)
);

CREATE INDEX idx_wallet_ledger_wallet_id ON wallet_ledger (wallet_id);

CREATE TABLE withdrawal_outcomes (
    transaction_id VARCHAR(64) NOT NULL PRIMARY KEY,
    wallet_id VARCHAR(36) NOT NULL,
    amount BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    balance_at_outcome BIGINT,
    ledger_entry_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_withdrawal_outcomes_wallet FOREIGN KEY (wallet_id) REFERENCES wallets (id),
    CONSTRAINT fk_withdrawal_outcomes_ledger FOREIGN KEY (ledger_entry_id) REFERENCES wallet_ledger (id)
);

CREATE INDEX idx_withdrawal_outcomes_wallet_id ON withdrawal_outcomes (wallet_id);
